version: "3.9"

x-env:
  &env
  env_file:
    - ./.env

services:
  db:
    image: mysql:8.0.29
    container_name: ${CONTAINER_NAME}-db
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - apacheroot=${APACHE_ROOT}
        - WP_THEME_PATH=${WP_THEME_PATH}
    container_name: ${CONTAINER_NAME}-web
    volumes:
      - ./app:${APACHE_ROOT}
    ports:
      - "443:443"
      - "80:80"
    <<: *env
    depends_on:
      - db

volumes:
  mysql-data: